# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=100000
SAVEHIST=100000
setopt appendhistory
unsetopt beep
bindkey -e
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/home/dstorch/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall

# Make prompt themes available.
autoload -Uz promptinit
promptinit

# Handle ssh-agent stuff to avoid re-typing ssh key password.
source $HOME/bin/ssh-agent-find.sh

# Ask me before deleting data.
alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'

# Set default editor.
export EDITOR=/usr/bin/vim
export VISUAL=/usr/bin/vim

export PATH=$HOME/bin:$PATH
export PATH=$HOME/bin/mongo-versions:$PATH
# Haskell stack executables.
export PATH=$HOME/.local/bin:$PATH

alias -g smoke='python3 buildscripts/resmoke.py'

# Ninja.
export NINJA_STATUS='[%f/%t (%p) %es] ' # Format ninja status output.
alias sconsninja='python3 buildscripts/scons.py MONGO_VERSION="0.0.0" MONGO_GIT_HASH="unknown" VARIANT_DIR=ninja CC=clang CXX=clang++ --link-model=dynamic --modules=ninja,enterprise --icecream build.ninja'
alias sconsninjadebug='python3 buildscripts/scons.py MONGO_VERSION="0.0.0" MONGO_GIT_HASH="unknown" VARIANT_DIR=ninja CC=clang CXX=clang++ --dbg=on --opt=off --modules=ninja,enterprise --icecream debug.ninja'
alias sconsninjagcc='python3 buildscripts/scons.py MONGO_VERSION="0.0.0" MONGO_GIT_HASH="unknown" VARIANT_DIR=ninja CC=/opt/mongodbtoolchain/v3/bin/gcc CXX=/opt/mongodbtoolchain/v3/bin/g++ --modules=ninja,enterprise --icecream gcc.ninja'
alias sconsninjacommunity='python3 buildscripts/scons.py MONGO_VERSION="0.0.0" MONGO_GIT_HASH="unknown" VARIANT_DIR=ninja CC=clang CXX=clang++ --link-model=dynamic --modules=ninja --icecream community.ninja'
alias nj='ninja -j 600 '
alias njd='ninja -f debug.ninja -j 600 '
alias njg='ninja -f gcc.ninja -j 600 '
alias njc='ninja -f community.ninja -j 600 '

# tmux.
alias tmux='TERM=screen-256color-bce tmux'
alias tm='tmux -CC attach'

# antigen fanciness.
source $HOME/bin/antigen.zsh
antigen use oh-my-zsh
antigen bundle git
antigen bundle command-not-found
antigen bundle zsh-users/zsh-syntax-highlighting
antigen theme robbyrussell
antigen apply

# fzf keybindings for fuzzy cntrl-r command history search.
source /usr/share/fzf/key-bindings.zsh

# Git aliases.
alias g='git '
alias gb='git branch '
alias gbd='git branch -D '
alias gc='git checkout '
alias gcb='git checkout -t -b '
alias gcm='git checkout master'
alias gd='git diff'
alias gds='git diff --stat'
alias gl='git log'
alias gls='git log --stat'
alias gm='git merge --ff-only '
alias gp='git pull '
alias gr='git rebase '
alias gri='git rebase -i '
alias grm='git rebase master'
alias gs='git status '
alias gsh='git show '
